### ISSUE TITLE
Notes menu needs better organization

### ISSUE THREAD

**Issue by hoodiek** [tsileo/microblog.pub#13]
the main menu for onboarding users to articles needs a lot of work to be considered viable in practice. a directly vertical list doesn't provide enough ability for users to compare topics and make a choice of what they want to read.
![image](https://user-images.githubusercontent.com/23704040/41990984-fe3cf19e-7a11-11e8-9321-ce52628ab478.png)
if you look at the screen in question, the menu for sorting articles is fine, but the articles themselves need better organization. two columns would be a good method of splitting up the content, and would resemble plume, with greater ability for users to discern between content. plume's offering is a good comparison point, as it shows how much more accessible the visual parity makes the content in question become
![image](https://user-images.githubusercontent.com/23704040/41990979-f8ce3fe2-7a11-11e8-9821-6996ff26638b.png)

**Comment by tsileo** [comment]
Hey!

I have to disagree with this, microblog.pub is a **micro**blog engine (VS a blog engine), the whole note is displayed on the index because it's not meant to host long posts/article, only short notes.

The layout will stay in one column.

Microblog.pub is more like a self-hosted mastodon/twitter, not like plume/wordpress.
Maybe I should try to make it more clear on the README.

Also, the project is under heavy development, the design is still a draft/changes often.

Thanks for the feedback, I'm closing the issue, I feel like it's too early to discuss design, and the specific point doesn't apply with the philosophy of the project.
