### ISSUE TITLE
Cannot make CSS on Ubuntu 18.04?

### ISSUE THREAD

**Issue by mitchellurgero** [tsileo/microblog.pub#24]
I get the following error(s) when running `make css`:

```
python -c "import sass; sass.compile(dirname=('sass', 'static/css'), output_style='compressed')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named sass
Makefile:4: recipe for target 'css' failed
make: *** [css] Error 1
```

I ran `pip install -r requirements.txt` already and it completes. did I miss a step or something?

Edit 1:
Manually running `python -c "import sass; sass.compile(dirname=('sass', 'static/css'), output_style='compressed')"` returns the following error too: `sass.CompileError: Error: Undefined variable: "$background-color".`

**Comment by tsileo** [comment]
Hey, it's because it's not needed anymore, this command should be removed, the CSS is compiled at the server startup and merged with the theme configuration (in the yaml file).

But I would recommend waiting for a stable release as I'm doing a lot of breaking changes these day in preparation for it.

**Comment by mitchellurgero** [comment]
That's amazing. I'll be a tester then. I am not running a fully-production server anyway :D
